### PR TITLE
Add Shane's info

### LINKED ISSUE #12: Add Shane's info

### PR DESCRIPTION
**Pull request by Shantaa**
closes #12

### CODE REVIEW

**Comment by meatyturtle** [comment]
hi @Shantaa kindly add in the PR description which issue this commit closes. thanks

**Comment by Shantaa** [comment]
> hi @Shantaa kindly add in the PR description which issue this commit closes. thanks

done sincere apologies

**Comment by fymbc** [comment]
> > hi @Shantaa kindly add in the PR description which issue this commit closes. thanks
> 
> done sincere apologies

Is this telegram?

**Comment by AlphaPyke** [comment]
it might be.

> > > hi @Shantaa kindly add in the PR description which issue this commit closes. thanks
> > 
> > 
> > done sincere apologies
> 
> Is this telegram?

**Pull request merged**
